os:
  - linux

language: cpp

compiler:
  - gcc

env:
  - HEIMDALI_DATA_DIR=$TRAVIS_BUILD_DIR/heimdali-data HEIMDALI_WORK_DIR=$TRAVIS_BUILD_DIR

before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels http://conda.binstar.org/heimdali
  - conda update conda
  - conda install conda-build pip jinja2
  - conda create -n inrimage inrimage
  - pip install lettuce
  - hash -r
  - conda info -a

install:
  - conda build --no-test conda-recipe/heimdali

script:
  - conda install --use-local heimdali
  - git clone https://github.com/heimdali/heimdali-data
  - cd tests
  - lettuce
