package:
  name: inrimage
  version: 4.6.6

source:
  fn: inrimage-4.6.6.tar.gz
  url: https://who.rocq.inria.fr/Dominique.Bereziat/ftp/inrimage/4.6.6/inrimage-4.6.6.tar.gz
  patches:
    - return_type_is_void.patch # [osx]

build:
  number: 0
  detect_binary_files_with_prefix: true

requirements:
  build:
    - system # [linux]
    - libxaw # [osx]
    - pkg-config # [osx]
    - libpng # [osx]
    - gfortran # [osx]
  run:
    - system # [linux]
    - libxaw # [osx]
    - libpng # [osx]
    - libgfortran # [osx]

test:
  files:
    - a-1o-s.inr 
  commands:
    - par a-1o-s.inr

about:
  home: http://inrimage.gforge.inria.fr/
