package:
  name: libxaw
  version: 1.0.11

source:
  fn: libXaw-1.0.11.tar.gz
  url: http://www.x.org/releases/X11R7.7/src/lib/libXaw-1.0.11.tar.gz

build:
  number: 0

requirements:
  build:
    - gcc ==4.8.4.99 # [linux]
    - pkg-config # [osx]
    - zlib
  run:
    - libgcc
    - zlib

about:
  home: http://www.x.org/wiki/
