package:
  name: tclap
  version: 1.2.1

source:
  fn: tclap-1.2.1.tar.gz
  url: http://downloads.sourceforge.net/project/tclap/tclap-1.2.1.tar.gz

build:
  number: 4
  binary_relocation: true

requirements:
  build:
    - gcc ==4.8.4.99
  run:
    - libgcc

about:
  home: http://tclap.sourceforge.net/
  license: MIT
