package:
  name: tclap
  version: 4.2.1

source:
  fn: tclap-1.2.1.tar.gz
  url: http://downloads.sourceforge.net/project/tclap/tclap-1.2.1.tar.gz

build:
  number: 2
  binary_relocation: true

about:
  home: http://tclap.sourceforge.net/
  license: MIT
