package:
  name: heimdali
  version: 0.7.2

source:
  path: ..
  #fn: heimdali-0.7.2.tar.gz
  #url: https://github.com/heimdali/heimdali/archive/0.7.2.tar.gz

build:
  number: 0
  binary_relocation: true

requirements:
  build:
    - cmake
    - tclap
    - itk-heimdali
    - h5unixpipe
    - libinrimage
  run:
    - tclap
    - itk-heimdali
    - h5unixpipe
    - libinrimage

test:
  commands:
    - par --help

about:
  home: https://github.com/heimdali/heimdali 
  license: GPL
