package:
  name: heimdali
  version: 0.7.2

script_env:
  - CONTINUOUS_INTEGRATION
  - TRAVIS

source:
  path: ../..
  #fn: heimdali-0.7.2.tar.gz
  #url: https://github.com/heimdali/heimdali/archive/0.7.2.tar.gz

build:
  number: 3
  binary_relocation: true

requirements:
  build:
    - gcc ==4.8.5
    - cmake
    - tclap
    - itk-heimdali
    - h5unixpipe
    - libinrimage
  run:
    - libgcc
    - tclap
    - itk-heimdali
    - h5unixpipe
    - libinrimage

test:
  commands:
    - par --help

about:
  home: https://github.com/heimdali/heimdali 
  license: GPL
