package:
  name: heimdali
  version: 0.7.3

source:
  path: ../.. # [USER == 'travis']
  fn: heimdali-0.7.3.tar.gz # [USER != 'travis']
  url: https://github.com/heimdali/heimdali/archive/0.7.3.tar.gz # [USER != 'travis']

build:
  number: 3
  binary_relocation: true
  script_env:
    - CONTINUOUS_INTEGRATION
    - TRAVIS

requirements:
  build:
    - gcc ==4.8.5 # [linux]
    - cmake
    - tclap
    - itk-heimdali
    - h5unixpipe
    - libinrimage
  run:
    - libgcc # [linux]
    - tclap
    - itk-heimdali
    - h5unixpipe
    - libinrimage

test:
  commands:
    - par --help

about:
  home: https://github.com/heimdali/heimdali 
  license: GPL
